### ISSUE TITLE
Resolve cache is trashed in partial lookup failure

### ISSUE THREAD

**Issue by suonpaa** [FoobarOy/foomuuri#13]
According to [documentation](https://github.com/FoobarOy/foomuuri/wiki/Configuration) the resolve cache should survive a single lookup failure or a reboot.

> Single lookup failure does not matter, Foomuuri will cache old results for 24h. These results are also saved for reloads and reboots.

This is not the case, if some of hosts fail to resolve . An example of such situation is when DNS resolution fails, but other means of resolution – such as /etc/hosts – still work.

How to reproduce? Like this.

Host in question is **deb.diurnalis.fi**.

/etc/hosts:
```
127.0.1.1	deb.diurnalis.fi	deb
```

/etc/foomuuri/foomuuri.conf includes deb.diurnalis.fi and some other host to be resolved.
```
[...]
resolve {
  @d		deb.diurnalis.fi 
  @b		bbbs.net
}
[...]
```

As name resolution works, Foomuuri resolve cache is sane:
```
# cat /var/lib/foomuuri/resolve.fw 
add element inet foomuuri d_4 { 127.0.1.1 }
delete element inet foomuuri d_4 { 127.0.1.1 }
add element inet foomuuri d_4 { 127.0.1.1 timeout 24h }
add element inet foomuuri b_4 { 213.216.205.19 }
delete element inet foomuuri b_4 { 213.216.205.19 }
add element inet foomuuri b_4 { 213.216.205.19 timeout 24h }
add element inet foomuuri b_6 { 2001:14ba:2e00:1900::1 }
delete element inet foomuuri b_6 { 2001:14ba:2e00:1900::1 }
add element inet foomuuri b_6 { 2001:14ba:2e00:1900::1 timeout 24h }
# 
```

Now let's shut down name resolution and see what happens, is foomuuri-resolve is run before getting name resolution back:
```
# systemctl stop unbound
# systemctl start foomuuri-resolve.service
# cat /var/lib/foomuuri/resolve.fw 
add element inet foomuuri d_4 { 127.0.1.1 }
delete element inet foomuuri d_4 { 127.0.1.1 }
add element inet foomuuri d_4 { 127.0.1.1 timeout 24h }
#
```
As deb.diurnalis.fi is resolved with /etc/hosts, while DNS resolutions is in a state of failure, I lose the whole resolve cache. I guess this should not be the case.

This quite likelyaffects reboot as well, as foomuuri will be started before unbound. I guess something like this would also happen when first of the names to be resolved is found in unbound's cache, while other fail to resolve?

Now, one might ask why in the name of everything that is holy am I trying to resolve the name of localhost? Fair enough.

I administer half a dozen systems. They all share foomuuri defaults, such as macros and templater, in /etc/foomuuri/defaults.conf. Because five of the systems need to have my smtp resolved as @smtp the smtp server ends up resolving itself, even though the address will not be used in any actual rule on this particular host.

**Comment by kimheino** [comment]
> > Single lookup failure does not matter, Foomuuri will cache old results for 24h. These results are also saved for reloads and reboots.
> 
> This is not the case, if some of hosts fail to resolve .

You are correct. Foomuuri doesn't cache failed lookups if there is reboot or restart. I need to fix that.

But it (or kernel actually) does cache failed lookups for 24h.

> cat /var/lib/foomuuri/resolve.fw 
> add element inet foomuuri d_4 { 127.0.1.1 }
> delete element inet foomuuri d_4 { 127.0.1.1 }
> add element inet foomuuri d_4 { 127.0.1.1 timeout 24h }

That refreshes successful lookup. Failed lookup is still there. Take a look at `nft list set inet foomuuri b_4`, it will show my IP with some expire timeout. `foomuuri start` will clear cache which I'll fix.

> This quite likelyaffects reboot as well, as foomuuri will be started before unbound. 

For this reason foomuuri-resolve will run three minutes after reboot, not immediately.

**Comment by kimheino** [comment]
Commit 928394a should fix this.
