### ISSUE TITLE
[RFE] Add a macro to support WSDD

### ISSUE THREAD

**Issue by ajayramaswamy** [FoobarOy/foomuuri#16]
[https://github.com/christgau/wsdd#firewall-setup](url)

wsdd implements a Web Service Discovery host daemon. This enables (Samba) hosts, like your local NAS device, to be found by Web Service Discovery Clients like Windows.

Firewall Setup
Traffic for the following ports, directions and addresses must be allowed.

incoming and outgoing traffic to udp/3702 with multicast destination:
239.255.255.250 for IPv4
ff02::c for IPv6
outgoing unicast traffic from udp/3702
incoming to tcp/5357
You should further restrict the traffic to the (link-)local subnet, e.g. by using the fe80::/10 address space for IPv6. Please note that IGMP traffic must be enabled in order to get IPv4 multicast traffic working.

For UFW, an application profile can be found under etc/ufw/applications.d. Note that UFW profile only allow to grant the traffic on specific UDP and TCP ports, but a restriction on the IP range (like link local for IPv6) or the multicast traffic is not possible.

I think this will be a good starting point

```
macro {
  wsdd udp 3702 daddr 239.255.255.250 ff02::c ; udp sport 3702 ; tcp dport  5357; multicast udp 3702;
}
```

**Comment by kimheino** [comment]
Thanks, added as `ws-discovery` as it's the official name for port 3702.
