### ISSUE TITLE
Feature request: NFLOG support

### ISSUE THREAD

**Issue by Talkless** [FoobarOy/foomuuri#17]
NFLOG logging target allows to capture firewall logs separately from syslogs (journal) using `ulogd2` daemon. It then can store logs in a plain text, JSON file or send to RDBMS.

Shorewall supports it:
https://shorewall.org/manpages/shorewall-logging.html#idm139715831569968

Firewalld's rich language mode supports it too: 
https://github.com/firewalld/firewalld/pull/720

**Comment by kimheino** [comment]
Can you verify if this works:

```
foomuuri {
  log_level "group 0"
}
```

Of course group can be any number you want to. You can also specify `queue-size number`  and other parameters after `group 0`.

This setting is global, not per rule. Do you need per-rule log groups?

**Comment by kimheino** [comment]
I tested:

```
foomuuri {
  log_level "group 30"
}
```

And then `tcpdump -i nflog:30 -nv` will see logged packets. This should work already in all old Foomuuri versions.

Is this enough for your needs? If so, then I'll just document this to wiki.

**Comment by kimheino** [comment]
Rule-specific version documents possible values: https://github.com/FoobarOy/foomuuri/wiki/Rule#log_level

All of those values should already work in `foomuuri { log_level "..." }`

**Comment by Talkless** [comment]
> Is this enough for your needs?

I'll try foomuuri in the weekend perhaps, to see if I see logs in ulogd2, thanks!

**Comment by Talkless** [comment]
OK sorry, I guess I lied about weekend - just installed it in Debia Sin VM, and added:
```
public-localhost {
    saddr 192.168.1.10 tcp dport 22 counter log reject
    ...
```

and

```
foomuuri {
    log_level group 0
}
```

and result was:

```
# tail -f /var/log/ulog/syslogemu.log 
Oct 23 20:57:17 debian-sid public-localhost REJECT  IN=enp0s3 OUT= MAC=08:00:27:8c:a6:35:08:62:66:b3:2e:1c:08:00 SRC=192.168.1.10 DST=192.168.1.179 LEN=60 TOS=10 PREC=0x00 TTL=64 ID=17496 DF PROTO=TCP SPT=35756 DPT=22 SEQ=4095113953 ACK=0 WINDOW=64240 SYN URGP=0 MARK=0x0
```

So it works! And whole setup was copy-paste from [Host Firewall](https://github.com/FoobarOy/foomuuri/wiki/Host-Firewall) example...
