### ISSUE TITLE
Feature request: UID/GID-based zones/matching?

### ISSUE THREAD

**Issue by Talkless** [FoobarOy/foomuuri#18]
Shorewall allows to match output patches by their uid/gid. This allows, for example, launching ABSOLUTELY PROPRIETARY `skypeforlinux` in `fw-skype` (or weather) group (using `sg fw-skype skypeforlinux`) and firewall output packets for that particular application.

Not sure what would be "foomuuri'iest" implementation, but Firewalld developers are pondering to use uid/group as a zone source: https://github.com/firewalld/firewalld/issues/725#issuecomment-1134776210

**Comment by kimheino** [comment]
This should work (=untested) for outgoing packets:

```
zone {
  skype
}

zonemap {
  uid skypeuser szone localhost new_szone skype
}

skype-public {
   ...
}
```

That maps source zone to skype, which sounds more logical mapping for me. You can also map destination zone (or both zones) if preferred:

```
zonemap {
  uid skypeuser dzone public new_dzone skype
}

localhost-skype {
}
```

See:

https://github.com/FoobarOy/foomuuri/wiki/Configuration#zonemap
https://github.com/FoobarOy/foomuuri/wiki/Rule#uid-gid

One more option is to not use zones:

```
localhost-public {
  uid skypeuser tcp 1234  # allow  single port
  uid skypeuser drop      # drop everything else
  .... normal rules ...
}
```

**Comment by Talkless** [comment]
Oh, so it's zone mapping that creates new zones. I've kinda skipped that part without getting deep into it.

Pretty good stuff, thanks for explanation!
