### ISSUE TITLE
dnat parsing issue with ipv6:port in 0.21

### ISSUE THREAD

**Issue by MeanBean** [FoobarOy/foomuuri#19]
Hi,

I've started using foomuuri since 0.20 like 1/2 months ago (the version available in debian 12 backport)
And I managed to use dnat with ipv6 this way:

`iifname vmbr0 ipv6 smtp dnat to [fdd4:xxxx:xxxx:xxxx::901]:smtp`

After upgrading to 0.21, it fails with this message:
`Invalid IP address in "to": [fdd4:xxxx:xxxx:xxxx::901]:smtp`

Tried as well without the ipv6 between [], but same result

It seems to be linked to those 2 commits https://github.com/FoobarOy/foomuuri/commit/a78e0315986665943e2652118ba416cef2d20d41 and https://github.com/FoobarOy/foomuuri/commit/83c31a95ece8455826705e9ae333ca275b894fea#diff-9f0b793b410a2900722f9711f10a798a3386efa6fecbdcdc4119ebea296281c1L1156

To my outside eye, it looks like you're not managing the last ':' for ipv6 and consider the whole string as the ip.
For ipv4, you have a special check for this AFAICS (`check_ipv = 4  # IPv4 address with port` lines 1166/1167).

Maybe I'm not following the syntax, but I did not find anything in the wiki for ipv6:port.

Thanks for the help.

**Comment by kimheino** [comment]
Commit ce75e2f should fix your problem. Another partly related commit is coming, but not needed for this.

Btw, it's enough to do:

```
iifname vmbr0 smtp dnat to [fdd4:xxxx:xxxx:xxxx::901]:smtp
```

without `ipv6` matcher. Foomuuri parses IP address and automatically handles this rule as IPv6 only.

**Comment by MeanBean** [comment]
Thanks.

I've got another dnat on ipv4 for vmbr0 smtp, hence the 2 lines when I tried to figure it out. Especially as it was not working at first.

Just cut/pasted your fix and removed ipv4/ipv6 and it's all good.
Thanks for the quick fix.

**Comment by kimheino** [comment]
Foomuuri's parser is funny and it will split this to two rules automatically:

```
iifname vmbr0 smtp dnat to 192.168.3.4:smtp [fdd4:1:2:4::901]:smtp
```

And, as you nat smtp to smtp, it's enough to do:

```
iifname vmbr0 smtp dnat to 192.168.3.4 fdd4:1:2:4::901
```

I'll improve wiki about this.

**Comment by MeanBean** [comment]
Thanks for the tip.
Yes, it would have been much easier for me with clear examples in the wiki.

Anyway, happy with the project and not having to write direct nft rules myself.
