### ISSUE TITLE
Make iplists refresh time configurable

### ISSUE THREAD

**Issue by Fregf** [FoobarOy/foomuuri#21]
It would be great if refresh time would be configurable per iplist. For example, I could have an iplist with all IPs from a cloud provider which I want to refresh only once per day. On the other hand, I could have an iplist of a blocklist (such as the one of https://lists.blocklist.de/) which I want to refresh every 5 minutes.

A solution would be to make the systemd timer run every 5 minutes, and then make it possible to configure the interval per iplist in the foomuuri configuration.

**Comment by kimheino** [comment]
Nice idea. Currently you can easily set interval for all lists with command `systemctl edit foomuuri-iplist.timer` and:

```
[Timer]
OnUnitActiveSec=5m
```

For future I was thinking about changing default OnUnitActiveSec from 24h to 15m (5m sounds too excessive?) and then adding timeout parameter for iplist:

```
iplist {
  @black   https://blacklist timeout=15m
  @another /read/my/file  # uses default timeout 24h
}
```

If you need faster than 15m then you have to use `systemctl edit`. 

Would this be enough for you?

**Comment by kimheino** [comment]
Another maybe-idea is to add command line `foomuuri iplist refresh @black` that would update black-iplist. That could be called from another program / cron / timer.

**Comment by kimheino** [comment]
Refresh interval can be configured [new in version 0.22] globally or
per-iplist with `refresh` option:

```
iplist {
  # Set global refresh interval
  refresh 4h15m

  # Use global refresh interval
  @blacklist  /etc/foomuuri/blacklist*.txt

  # Use per-iplist refresh interval
  @whitelist  /etc/foomuuri/whitelist*.txt refresh=1h15m
}
```

Interval is rounded to 15 minutes. This can be configured with
`systemctl edit foomuuri-iplist.timer` command.
