### ISSUE TITLE
foomuuri as stand-alone generator

### ISSUE THREAD

**Issue by nicolas314** [FoobarOy/foomuuri#22]
Thanks for this great project! `nftables` was really missing a zone-based rule production tool, this fills the gap quite nicely.
I wanted to try it out on an unspported linux distro (alpine, openrc-based) and was wondering if there is an easy way to use foomuuri as a stand-alone generator? You would point it to a directory containing the `.conf` files and let it generate an `nftables.conf` output which you can then export to a firewall. Not as good as running it locally of course, but would be useful.

**Comment by kimheino** [comment]
> I wanted to try it out on an unspported linux distro (alpine, openrc-based) and was wondering if there is an easy way to use foomuuri as a stand-alone generator?

Yes there is (undocumented):

```
(12:26) b@cobra:~/22> ls -laR
.:
total 236
drwxr-xr-x. 1 b b     32 Dec 17 12:26 .
drwx------. 1 b b   1586 Dec 17 12:24 ..
drwxr-xr-x. 1 b b     26 Dec 17 12:16 etc
-rwxr-xr-x. 1 b b 115587 Dec 17 12:25 foomuuri
drwxr-xr-x. 1 b b     62 Dec 17 12:13 share

./etc:
total 8
drwxr-xr-x. 1 b b   26 Dec 17 12:16 .
drwxr-xr-x. 1 b b   32 Dec 17 12:26 ..
-rw-r--r--. 1 b b 6612 Dec 17 12:16 foomuuri.conf

./share:
total 8
drwxr-xr-x. 1 b b   62 Dec 17 12:13 .
drwxr-xr-x. 1 b b   32 Dec 17 12:26 ..
-rw-r--r--. 1 b b 3549 Dec 17 12:13 default.services.conf
-rw-r--r--. 1 b b  974 Dec 17 12:13 static.nft

(12:27) b@cobra:~/22> ./foomuuri --set=etc_dir=./etc --set=share_dir=./share --set=state_dir=. check
Warning: Foomuuri should be run as "root"
netlink: Error: cache initialization failed: Operation not permitted
Error: Nftables failed to check ruleset, error code 1

(12:27) b@cobra:~/22$ ls -la next.fw 
-rw-------. 1 b b 34341 Dec 17 12:27 next.fw
```

Then you can load next.fw with `nft -f next.fw`. I assume your system can load it automatically if saved as `/etc/nftables/main.nft`.

You can get rid of warning+error by running it as root:

```
(12:28) b@cobra:~/22> sudo ./foomuuri --set=etc_dir=./etc --set=share_dir=./share --set=state_dir=. check
check success

(12:29) b@cobra:~/22> ls -la next.fw 
-rw-------. 1 root root 34341 Dec 17 12:29 next.fw
```

There seems to be a small bug in state_dir handler. It has to be `.` or full path, relative doesn't work. I'll fix that to next release.

See also `etc/50-foomuuri.conf` file. You probably want to copy it to `/etc/sysctl.d/` in your firewall.

**Comment by kimheino** [comment]
Above two commits fixes relative directory and non-root:

```
(10:59) b@cobra:~/22> ./foomuuri --set=etc_dir=./etc --set=share_dir=./share --set=state_dir=output check
Warning: Foomuuri should be run as "root"
check success
(11:00) b@cobra:~/22> ls -l output/
total 40
-rw-------. 1 b b 34341 Dec 18 11:00 next.fw
-rw-------. 1 b b    31 Dec 18 11:00 zone
(11:00) b@cobra:~/22> 
```

**Comment by nicolas314** [comment]
Fantastic, thanks a lot!
