### ISSUE TITLE
Wishlist: option to reject / drop routing to rfc1918 on an interface

### ISSUE THREAD

**Issue by suonpaa** [FoobarOy/foomuuri#24]
My iPhone regularly tries to connect tcp 7000 on 192.168.0.0 network. I really do not know why. Most likely it is searching for an Apple TV my neighbour might have, which has been advertising its' existence with bluetooth. Or whatever Apple does. I really do not care.

Anyway, I really do not want my router to even try routing anything to any private networks on WAN.

With Shorewall, I believe I had something like this in /etc/shorewall/interfaces:

```
#ZONE	INTERFACE	OPTIONS
net     eth0            norfc1918
```

With foomuuri, should I just block the private network ranges or is there some other way I could say: "This is public network. Let's not pollute it with this crap."

**Comment by bleve** [comment]
That is better handled in system network configurations.

Just add unreachable routes for rfc1918 networks. With iproute2 that is:

```
# Responde with no route to host for rfc1918
ip route add unreachable 192.168.0.0/16 metric 1024
ip route add unreachable 172.16.0.0/12 metric 1024
ip route add unreachable 10.0.0.0/8 metric 1024
```

This doesn't interrupt any local rfc1918 networks because those have more specific routes on your routing table.

**Comment by suonpaa** [comment]
Never thought of that. Thanks. This should do it.

**Comment by kimheino** [comment]
As bleve said, it's better to handle this in routing tables. Above routes can be added in Debian-specific way (`/etc/network/something`), or from Foomuuri's `post_start` hook, or by NetworkManager. 

To use NetworkManager edit `/etc/NetworkManager/system-connections/<doesn't-really-matter-which>.nmconnection` file and add lines

```
[ipv4]
...
route1=0.0.0.0/8,0.0.0.0,1024
route1_options=type=unreachable
route2=10.0.0.0/8,0.0.0.0,1024
route2_options=type=unreachable
route3=100.64.0.0/10,0.0.0.0,1024
route3_options=type=unreachable
route4=169.254.0.0/16,0.0.0.0,1024
route4_options=type=unreachable
route5=172.16.0.0/12,0.0.0.0,1024
route5_options=type=unreachable
route6=192.0.0.0/24,0.0.0.0,1024
route6_options=type=unreachable
route7=192.0.2.0/24,0.0.0.0,1024
route7_options=type=unreachable
route8=192.168.0.0/16,0.0.0.0,1024
route8_options=type=unreachable
route9=198.18.0.0/15,0.0.0.0,1024
route9_options=type=unreachable
route10=198.51.100.0/24,0.0.0.0,1024
route10_options=type=unreachable
route11=203.0.113.0/24,0.0.0.0,1024
route11_options=type=unreachable

[ipv6]
...
route1=<your-ipv6-network-prefix>,::,1024
route1_options=type=blackhole
route2=2001:2::/48,::,1024
route2_options=type=unreachable
route3=2001:10::/28,::,1024
route3_options=type=unreachable
route4=2001:db8::/32,::,1024
route4_options=type=unreachable
route5=fc00::/7,::,1024
route5_options=type=unreachable
```

Or in this specific case use Foomuuri's basic rules:

```
internal-public {
  daddr 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 drop
}
```
