### ISSUE TITLE
Syntaxc Error 'reject with icmpx admin-prohibited'

### ISSUE THREAD

**Issue by jens4topsnet** [FoobarOy/foomuuri#27]
I found a misstake in foomuuri reject rule.

Foomuuri create a nft rule with 'reject with icmpx admin-prohibited'. This syntax is not correct. The 'type' is missing.
The correct syntax is 'reject with icmpx type admin-prohibited'

Here is my working patch:
```
--- foomuuri-0.22.orig/src/foomuuri
+++ foomuuri-0.22/src/foomuuri
@@ -700,7 +700,7 @@ def parse_rule_line(fileline_line):
             ret['policy'] = item
             keyword = None
         elif item == 'reject':
-            ret['policy'] = 'reject with icmpx admin-prohibited'
+            ret['policy'] = 'reject with icmpx type admin-prohibited'
             keyword = None
         elif item in ('multicast', 'broadcast'):
             ret['cast'] = item
@@ -1632,7 +1632,7 @@ def output_header():
     out(f'type filter hook output priority filter{CONFIG["priority_offset"]}')
     out('oifname vmap @output_zones')
     output_static_chain_logging('output', 'reject')
-    out('reject with icmpx admin-prohibited')
+    out('reject with icmpx type admin-prohibited')
     out('}')

     out('chain forward {')
```
Best regards
--
Jens

**Comment by rfrancoise** [comment]
`reject with icmpx <code>` is the new syntax as of nftables 1.0.0 (which contains [this commit](https://git.netfilter.org/nftables/commit/?id=08d2f049367153d2c3b03c95b2ca7256cdf3521d)). You're probably using an older release, and I would strongly suggest upgrading to a more modern one.

**Comment by jens4topsnet** [comment]
Oh yes. Thank you for this notice. 
We use debian 11 and ubuntu 20LTS. Both systems have nftables version 0.9x. My patch is only need for this OS versions. 
I have try to update nftables to version 1.x on ubuntu 20. It is too hard. The better way ist update ubuntu to version 22LTS.
Best Regards
