### ISSUE TITLE
foomuuri check fails with suggested log_level

### ISSUE THREAD

**Issue by lx1** [FoobarOy/foomuuri#3]
I'm trying foomuuri. With the default conf suggested in the wiki, in the foomuuri section there is a line:
log_level "level info"

With that line in place, foomuuri check gives errors (at least on my Alma linux 9):
\# foomuuri check
/var/lib/foomuuri/next.fw:61:115-115: Error: syntax error, unexpected newline
                update @_lograte_set_4 { ip saddr limit rate 1/second burst 3 packets } log prefix "RPFILTER DROP " "level info"
                                                                                                                                ^
/var/lib/foomuuri/next.fw:62:116-116: Error: syntax error, unexpected newline
                update @_lograte_set_6 { ip6 saddr limit rate 1/second burst 3 packets } log prefix "RPFILTER DROP " "level info"
                                                                                                                                 ^ 

If I remove the quotes, the error seems to be resolved.

**Comment by bleve** [comment]
Sorry. That was an error in documentation, uotes should not be used there.

I fixed the documentation.

**Comment by kimheino** [comment]
Commit  dbaa4c7  fixes parser to support quotes in foomuuri{} section.  I'll re-add them to documentation too, as I prefer having them there (log level and rate limit).

Foomuuri will work fine with and without quotes in log_level.
