### ISSUE TITLE
iplist fails to import emergingthreats blocklist

### ISSUE THREAD

**Issue by Fregf** [FoobarOy/foomuuri#42]
I wanted to import https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt so I set in the iplist section:
`@et https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt`

And added a block rule for this iplist in my public-localhost section.

This resulted in this error:

```
# foomuuri reload
start success
/var/lib/foomuuri/iplist.fw:43264:34-46: Error: conflicting intervals specified
add element inet foomuuri et_4 { xxx.xxx.xxx.xxx/24 timeout 10d }
                                 ^^^^^^^^^^^^^
Error: Failed to update iplist, error code 1

```
I guess maybe iplist only supports individual IP addresses and does not support CIDR notation?
Is there a way to import this lists in Foomuuri?

**Comment by kimheino** [comment]
That list has following overlapping entries:

5.188.10.0/23
5.188.11.0/24

Nftables rejects this with "Error: conflicting intervals specified". Above commit allows this by enabling nftables's `auto-merge` option.

This overlap error should be reported to Emerging Threats list maintainer.
