### ISSUE TITLE
rule/macro for ospf protocol

### ISSUE THREAD

**Issue by avlubimov** [FoobarOy/foomuuri#48]
Rule for ospf protocol does not work

I found an ospf macro but it's clearly not what I need.
 
`ospf multicast protocol "ospf" daddr 224.0.0.5 224.0.0.6 ff02::5 ff02::6 fe80::/10
`
ospfd used its own protocol #89

In shorewall the rule looks like this:

`ACCEPT $FW vpn:224.0.0.0/4 89
`
What's it like here?

**Comment by bleve** [comment]
Why do you think macro doesn't work?

**Comment by avlubimov** [comment]
> Why do you think macro doesn't work?

I think the OSPF macro is not working because when I use it, frr ospfd does not receive the routes. And when I allow all traffic, it works.

for example, like this:

```
vpn-localhost {
 ospf
}

localhost-vpn {
 ospf
}

```

but  works 

```
vpn-localhost {
 accept
}

localhost-vpn {
 accept
}

```

**Comment by kimheino** [comment]
Please include syslog/journal log entries where these packets are dropped or rejected when using ospf macro.

**Comment by kimheino** [comment]
Ping? Do you still see this problem? Can you provide log entries for drop/reject?

**Comment by kimheino** [comment]
Closing this issue. Reopen when logs are provided.

**Comment by kimheino** [comment]
I asked about this on netfilter channel on IRC. Switching to `fib daddr` should be safe and better. I will do it.
