### ISSUE TITLE
[RFE] also take into account other nft rules on the system

### ISSUE THREAD

**Issue by ajayramaswamy** [FoobarOy/foomuuri#7]
Look at the comment at the top of /etc/nftables/main.nft
``# Sample configuration for nftables service.
# Load this by calling 'nft -f /etc/nftables/main.nft'.

# Note about base chain priorities:
# The priority values used in these sample configs are
# offset by 20 in order to avoid ambiguity when firewalld
# is also running which uses an offset of 10. This means
# that packets will traverse firewalld first and if not
# dropped/rejected there will hit the chains defined here.
# Chains created by iptables, ebtables and arptables tools
# do not use an offset, so those chains are traversed first
# in any case.
``

In my case i see rules added by systemd-networkd and tailscale

**Comment by kimheino** [comment]
I added `chain_priority` config option, defaulting to 5.

Priority doesn't matter that much as netfilter will run all chains anyway before packet is accepted.
