### ISSUE TITLE
[Question] How to do Hairpin NAT or NAT Loopback

### ISSUE THREAD

**Issue by ajayramaswamy** [FoobarOy/foomuuri#8]
Please update the wiki with an example

**Comment by kimheino** [comment]
This snippet worked for me:

```
dnat {
  daddr 213.216.205.19 tcp 2224 dnat to 10.4.2.136:22
}

snat {
  saddr 10.4.2.0/24 daddr 10.4.2.136 ssh snat to 10.4.2.1
}

# LAN access
internal-internal {
  ssh
}

# Public access
public-internal {
  ssh
}
```

213.216.205.19 is my firewall's public IP, 10.4.2.1 is it's internal IP
10.4.2.0/24 is my LAN
10.4.2.136 is server on my LAN

From another computer on my LAN I was able to do "ssh 213.216.205.19 -p 2224". Of course you can use standard port instead of 2224.
